apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: lab4
spec:
  containers:
  - name: container1
    image: nginx
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: lab4
spec:
  containers:
  - name: container2
    image: nginx
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: lab4
spec:
  containers:
  - name: container3
    image: nginx
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: lab4
spec:
  containers:
  - name: container4
    image: nginx
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
  namespace: lab4
spec:
  containers:
  - name: container5
    image: nginx
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
